---
apiVersion: sedai.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    owner: currencyTeam
  name: currencyservice-slo
  namespace: google-examples
service: currencyservice
spec:
  slos:
    - target: "99"
      window: 2w
      description: Latency Indicator
      indicator:
        ratio:
          numeratorMetrics:
            metric: istio.mesh.request.duration.milliseconds.sum
          denominatorMetrics:
            metric: istio.mesh.request.duration.milliseconds.count
      
