---
apiVersion: sedai.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    owner: currencyTeam
    environment: production
    app: currencyservice
  namespace: google-examples
  name: currencyservice-slo
spec:
  slos:
    - target: "99"
      window: 2w
      name: "Latecy"
      description: "99 % of the requests should have latency less than 5ms for successful"
      indicator:
        raw:
          rawMetric: 
            successMetricName: istio.mesh.request.duration.milliseconds
            category: LATENCY
            sliAggregationIntervalms: "120000"
            sliAggregationStats: avg
            latencyThreshold: "100"
            latencyOperator: le 
            filters:
              - key: response_code
                value: "5.*"
                operator: "!~"
    - target: "99"
      window: 2w
      name: "Availability"
      description: "99% of the requests should be successful"
      indicator:
        requestRatio:
          requestMetric: 
            category: AVAILABILITY
            numeratorSuccessMetrics: 
              metricName: istio.mesh.request.duration.milliseconds.count
              filters: 
                - key: code
                  value: "5.*"
                  operator: "=~"
            denominatorTotalMetrics: 
              metricName: istio.mesh.request.duration.milliseconds.count
            sliAggregationIntervalms: "120000"
              

      
