---
apiVersion: sedai.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    owner: adServiceTeam
    environment: production
    app: adservice 
  name: adservice-slo
  namespace: google-examples
spec:
  slos:
    - target: "99"
      window: 2w
      name: "Latency"
      description: "99 % of the requests should have latency less than 100ms"
      indicator:
        raw:
          rawQueryLanguage:
            qlType: promql 
            successQuery: avg_over_time(avg(rate(istio_request_duration_milliseconds_sum{destination_service_name="adservice",  destination_service_namespace="google-examples"}[2m:])/rate(istio_request_duration_milliseconds_count{destination_service_name="adservice",destination_service_namespace="google-examples"}[2m:])) by (destination_service_name,destination_service_namespace)[5m:])
            category: LATENCY
            latencyThreshold: "100"
            latencyOperator: le        
            sliAggregationIntervalms: "300000"
            sliAggregationStats: avg
    - target: "99"
      window: 2w
      name: "Availability"
      description: "99% of the requests should be successful"
      indicator:
        requestRatio:
          requestQueryLanguage: 
            qlType: promql 
            category: AVAILABILITY
            numeratorSuccessQuery: sum(rate(istio_request_duration_milliseconds_count{destination_service_name="adservice", destination_service_namespace="google-examples",response_code!~"5.*"}[5m]))
            denominatorTotalQuery: sum(rate(istio_request_duration_milliseconds_count{destination_service_name="adservice", destination_service_namespace="google-examples"}[5m]))
    - target: "99"
      window: 2w
      name: "LatencyRatio"
      description: "99% of the requests should be successful"
      indicator:
        requestRatio:
          requestQueryLanguage: 
            qlType: promql 
            category: LATENCY
            numeratorSuccessQuery: istio_request_duration_milliseconds_bucket{destination_service_name="adservice", destination_service_namespace="google-examples",le="0.1"}
            denominatorTotalQuery: istio_request_duration_milliseconds_count{destination_service_name="adservice", destination_service_namespace="google-examples"}

              

      
