---
apiVersion: sedai.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    owner: currencyTeam
  name: currencyservice-slo
  namespace: google-examples
spec:
  namespace: google-examples
  service: currencyservice
  slos:
    - target: "99"
      window: 2w
      name: "Latecy"
      description: "99 % of the requests should have latency less than 5ms"
      indicator:
        raw:
          rawMetric: 
            metricName: istio.mesh.request.duration.milliseconds
            category: LATENCY
            sliAggregationIntervalMS: "300"
            sliAggregationStats: avg
            filters:
              - key: latencyThreshold
                value: "5"
                operator: "="
              - key: latencyOperator
                value: le
                operator: "="
    - target: "99"
      window: 2w
      name: "Availability"
      description: "99% of the requests should be successful"
      indicator:
        requestRatio:
          requestMetric: 
            category: AVAILABILITY
            numeratorMetrics: 
              metricName: istio.mesh.request.duration.milliseconds.count
              filters: 
                - key: code
                  value: "5.*"
                  operator: "!~"
            denominatorMetrics: 
              metricName: istio.mesh.request.duration.milliseconds.count
            sliAggregationIntervalMS: "300"
            sliAggregationStats: avg
              

      
