---
apiVersion: sedai.dev/v1beta1
kind: ServiceLevelObjective
metadata:
  labels:
    owner: adServiceTeam
    environment: production
    app: adservice 
  name: adservice-slo
  namespace: google-examples
spec:
  slos:
    - target: "99"
      window: 2w
      name: "Latency"
      description: "99 % of the requests should have latency less than 30ms over a 2 week window"
      scope: NONE
      indicator:
        raw:
          rawQueryLanguage:
            qlType: promql 
            successQuery: avg(rate(istio_request_duration_milliseconds_sum{destination_service_name="adservice",destination_service_namespace="google-examples"}[2m:])/rate(istio_request_duration_milliseconds_count{destination_service_name="adservice",destination_service_namespace="google-examples"}[2m:])) by (destination_service_name,destination_service_namespace))
            category: LATENCY
            sliThreshold: "30"
            thresholdOperator: le
            sliAggregationIntervalSeconds: "300"
            sliAggregationStats: avg
    - target: "99"
      window: 2w
      name: "Availability"
      description: "99% of the requests should be successful over a 2 week window"
      scope: OPTIMIZATION_ONLY
      indicator:
        requestRatio:
          requestQueryLanguage: 
            qlType: promql 
            category: AVAILABILITY
            numeratorSuccessQuery: sum(rate(istio_request_duration_milliseconds_count{destination_service_name="adservice", destination_service_namespace="google-examples",response_code!~"5.*"}[5m]))
            denominatorTotalQuery: sum(rate(istio_request_duration_milliseconds_count{destination_service_name="adservice", destination_service_namespace="google-examples"}[5m]))
            sliAggregationIntervalSeconds: "300"
    - target: "99"
      window: 2w
      name: "LatencyRatio"
      description: "99% of the requests should have latency under 5 ms over a 2 week window"
      indicator:
        requestRatio:
          requestQueryLanguage: 
            qlType: promql 
            category: LATENCY
            numeratorSuccessQuery: istio_request_duration_milliseconds_bucket{destination_service_name="adservice", destination_service_namespace="google-examples",le="5"}
            denominatorTotalQuery: istio_request_duration_milliseconds_count{destination_service_name="adservice", destination_service_namespace="google-examples"}
            sliAggregationIntervalSeconds: "600"
