---
apiVersion: sedai.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    owner: currencyTeam
  name: currencyservice-slo
  namespace: google-examples
service: currencyservice
spec:
  slos:
    - target: "99"
      window: 2w
      name: "Latecy SLO for Currency Service with raw indicator for averaged available latency 5min"
      description: "99 % of the requests should have latency less than 5ms"
      indicator:
        raw:
          metrics: 
            metric: istio.mesh.request.duration.milliseconds
            sliAggregationInterval: "300"
            sliAggregationStats: avg
            filters:
              - key: latencyThreshold
                value: "5"
                operator: "="
              - key: latencyOperator
                value: le
                operator: "="
    - target: "99"
      window: 2w
      name: "Availability SLO for Currency Service with ratio indicator for averaged 5min"
      description: "99% of the requests should be successful"
      indicator:
        requestRatio:
          metrics: 
            numeratorMetrics: 
              metric: istio.mesh.request.duration.milliseconds.count
              filters: 
                - key: code
                  value: "5.*"
                  operator: "!~"
            denominatorMetrics: 
              metric: istio.mesh.request.duration.milliseconds.count
            sliAggregationInterval: "300"
            sliAggregationStats: avg
              

      
